name: Check X Value Daily

on:
  schedule:
    - cron: '11 00 * * *'  # 13:40 МСК (10:10 UTC)
  workflow_dispatch:       # Разрешает ручной запуск

jobs:
  check-x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Check X value
        id: x-check
        run: |
          node <<EOF
          const puppeteer = require('puppeteer');

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            
            await page.goto('https://site-65141.taptop.site/page-7');
            
            const xValue = await page.evaluate(() => {
              return document.querySelector('.textx span').textContent.trim();
            });
            
            console.log('Значение x:', xValue);
            
            // Формируем выходные данные для GitHub Actions
            if (xValue === '100') {
              console.log('::error::Обнаружено x=100!');
              process.exit(1);  // Падаем с ошибкой
            } else {
              console.log('::notice::Тест пройден. x =', xValue);
            }
            
            await browser.close();
          })();
          EOF

      - name: Success Notification
        if: success()
        run: |
          echo "✅ Тест успешно пройден"
          echo "Последнее значение x: ${{ steps.x-check.outputs.x-value }}"
